# Generated by Django 5.2.17 on 2026-09-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroacademico',
            unique_together={('alumno', 'asignatura')},
        ),
    ]
