# Generated by Django 5.2.17 on 2026-09-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registroacademico_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='matriculado',
            new_name='estado_matricula',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(default='Sin asignar', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registroacademico',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
