# Generated by Django 5.2.17 on 2026-09-15 05:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_matriculado_alumno_estado_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='registroacademico',
            options={'verbose_name': 'Registro Académico', 'verbose_name_plural': 'Registros Académicos'},
        ),
        migrations.AlterUniqueTogether(
            name='registroacademico',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registroacademico',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.alumno'),
        ),
        migrations.AlterField(
            model_name='registroacademico',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)]),
        ),
        migrations.AlterField(
            model_name='registroacademico',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='api.docente'),
        ),
        migrations.AddConstraint(
            model_name='registroacademico',
            constraint=models.UniqueConstraint(fields=('alumno', 'asignatura'), name='unique_alumno_asignatura'),
        ),
    ]
